### ISSUE TITLE
Link to the repository form the Wiki Page is broken

### ISSUE THREAD

**Issue by flowerkowski** [kevchant/AzureDevOps-ServerlessSQLPool-HomemadeDBProject#3]
The link to the repository on the Wiki page is not leading to this:

https://github.com/kevchant/AzureDevOps-ServerlessSQLPool-HomemadeDBProject

Instead, it leads to this:

https://github.com/kevchant/AzDo-ServerlessSQLPool-HomemadeDBProject 

And you get a 404 error :), small issue but just thought you could use the hint to correct this.

Thanks,
Dejan

**Comment by kevchant** [comment]
Thanks for pointing this out, was the link to the original repository where I created the initial wiki.

**Comment by flowerkowski** [comment]
No problem.
